import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.css";
import Navbar from "./Components/Navbar";
import { NavbarProps } from "./Interfaces/interfaces";
import Footer from "./Components/Footer";
import { footerData } from "./data/data";


const podcastFont = localFont({
      src: './fonts/Podcast.ttf', 
      variable: '--font-podcast', 
});
const openSans = Open_Sans({
      variable: "--font-open-sans",
      subsets: ["latin"],
});
export const metadata: Metadata = {
      title: "Travel",
      description: "Generated by create next app",
};

const navbarData: NavbarProps = {
      image: {
            src: "/logo.png",
            alt: "Logo_Icon",
            width: 133,
            height: 130
      },
      links: [
            { name: "Home", href: "/" },
            { name: "About Us", href: "/about" },
            { name: "Tour Packages", href: "" },
            { name: "Contact Us", href: "/contact" },
      ]
};

export default function RootLayout({
      children,
      modal
}: Readonly<{
      children: React.ReactNode;
      modal: React.ReactNode;
}>) {
      return (
            <html lang="en">
                  <body
                        className={`${openSans.variable} ${podcastFont.variable} antialiased bg-white`}
                  >
                        <div></div>
                        <Navbar image={navbarData.image} links={navbarData.links}></Navbar>
                        {children}
                        {modal}
                        <Footer data={footerData} />
                  </body>
            </html>
      );
}
